import type { Metadata } from "next";

import ThirdwebWallet from "./ThirdwebWallet"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="w-full h-full">

        <ThirdwebWallet />
        {children}
    
    </main>
  );
}
